language: scala
scala:
- 2.11.8
deploy:
  provider: heroku
  api_key:
    secure: VlB421U75qB74Yh8sgFmmM1uIcWq39tlPVRWGrOPTrG79wlvTO/xerzoPJqc23O6NewrdyW/FOqdqHfQJyTLUavPDvGMDLX+rR5Twy73yuFAKtDu9U6imWOjOzX1o7lser4uM8UQUOOg2pm2pKl9YctuJfVfJQpwlo2Q+sD4j19bCCkS7WJzVpIEOCQF2jTLhZs0KFuG8z+hf5FqoHMN0mdPKlsp1Eq61wL34jkb3ZGmxDQFU+V4MlytHS3imcZ2dzDLY43Tc2wUShCshsIN8JitWVX7v8OyjPLhzrHp34sWnyODxadR/EJ+o80sBwPVHUEANJ78uyWNf5S9TxdIFqXe/fFla0yKDsh3MJH06HolF3pPWy/PbMQyZGBQHRqcDkL1uLGUQ/N8K2jIGWiX5uFE+kXUqjTJD4CaR2s+Jh5cE5Rcuz3KYnnrqlA4RkCiBsGrVUMUlA5CWMYRhQyA4K3C0YYBjd3aQ0r7yTsKxl0N3KF/KTC4Odci+vKwBAGPwAZkx57VsUlY8Qm2CXIaHEU1ln2d8rF8ZyP9QnSrqEpuNfPWm9K4CN++45XfJ0Htzp6aUkdVvyh1KhowlgTQGfPB7CBH+ZsVMOVdSP67lZ+n5UGZYUz+GE7Mqw8DrxRkK+isXNeyL3+eh6YijV+3cRB366QSFn1n5xCtrJsQIs0=